# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64d533696f60cfbb69e504a18583d82796075aab475fd990a3aac4cf124a9ee319ca21612ff3c2d151f20956eba733a789b77771eaa70b658f7194140a5e5fe2

test:
  secret_key_base: 6ddcbbbf50e2e74c40ff81824d0752a6466b52241cca21eb7b57e213966520bc4c82e5436ab21bb125ce3d9062c17de8b7d9f5b057b5323c7e5c2acb8262f2f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
